---
apiVersion: v1
kind: Service
metadata:
  name: fah-cpu
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"http-port":"HTTP"}'
  labels:
    app: fah-cpu
spec:
  type: NodePort
  selector:
    app: fah-cpu
  ports:
  - name: http-port
    port: 80
    targetPort: 7396
